---

- name: ({{ ansible_distribution }}) Download Maven Archive ( URL = {{ url }}, DEST = {{ downloaded_file }})
  get_url:
   url: "{{ url }}"
   dest: "{{ downloaded_file }}"
   checksum: "md5:{{ url }}.md5"
