---

- name: ({{ ansible_distribution }}) Check Maven minimum version (maven_v_major >= 3)
  fail:
   msg: "Vérifier la version de maven que vous souhaitez installer : MIN V3+"
  when:
   maven_v_major|int < 3
