---

- name: Define installation directory for maven
  set_fact:
   install_dir: "/opt/maven"
   base_url: "https://archive.apache.org/dist/maven"

- name: Ensure final Maven root installation directory exists
  file:
   path: "{{ install_dir }}"
   state: directory
