---

- name: Create installation directories
  file:
   path: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   state: directory
  with_items: "{{ __maven_packages }}"

- name: Unarchive Downloaded maven archives
  unarchive:
   src: "{{ dest_archive | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   dest: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   creates: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}/bin/mvn"
   remote_src: true
   extra_opts:
    - --strip-components=1
  with_items: "{{ __maven_packages }}"

- name: Find all script files
  find:
   file_type: file
   paths: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}/bin/"
   patterns: "mvn,mvnDebug"
   recurse: false
   use_regex: false
  with_items: "{{ __maven_packages }}"
  register: scripts_find_result

- name: Set execution right to script files
  file:
   dest: "{{ item.path }}"
   mode: "a+rx"
  with_items: "{{ scripts_find_result.files }}"

- name: Make sure /etc/profile.d/ directory exists
  file:
   path: "/etc/profile.d/"
   mode: 0755
   state: directory

- name: Set the M2_HOME
  template:
   src: "templates/maven_home.sh.j2"
   dest: "/etc/profile.d/maven_home.sh"
   mode: a+x
  with_items: "{{ __maven_packages }}"
  when:
   - item.default
