---

- name: Create installation directories
  file:
   path: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   state: directory
  with_items: "{{ __maven_packages }}"

- name: Unarchive Downloaded maven archives
  unarchive:
   src: "{{ dest_archive | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   dest: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}"
   creates: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}/bin/mvn"
   remote_src: true
   extra_opts:
    - --strip-components=1
  with_items: "{{ __maven_packages }}"

- name: Find all script files
  find:
   file_type: file
   paths: "{{ install_dir | replace('$v_major', item.v_major) | replace('$v_minor', item.v_minor) }}/bin/"
   patterns: "mvn,mvnDebug"
   recurse: false
   use_regex: false
  with_items: "{{ __maven_packages }}"
  register: scripts_find_result

- name: Set execution right to script files
  file:
   dest: "{{ item.path }}"
   mode: "a+rx"
  with_items: "{{ scripts_find_result.results[0].files }}"

- name: Set the Maven bin commands links in /usr/bin/
  file:
   src: "{{ install_dir | replace('$v_major', item[0].v_major) | replace('$v_minor', item[0].v_minor) }}/bin/{{ item[1] }}"
   dest: "/usr/bin/{{ item[1] }}"
   state: link
   mode: a+x
  with_nested:
   - "{{ __maven_packages }}"
   - ['mvn', 'mvnDebug']
  when:
   - item[0].default
