---
- name: Converge
  hosts: all

  roles:
   - role: jetune.java
     vars:
      from_repo: false
      implementation: OPENJDK
      v_major: 11
      v_minor: 0.1
      build: 13
      os: linux
      arch: x64
      checksum: sha256:7a6bb980b9c91c478421f865087ad2d69086a0583aeeb9e69204785e8e97dcfd
      alternative_priority: 300
      is_default: true

   - role: ansible-role-maven
     vars:
      maven_v_major: 3
      maven_v_minor: 6.1
      maven_is_default: true
      maven_user: "root"
      maven_group: "root"
      maven_local_repository: "/opt/maven/repository"
      maven_proxies:
       - id: "cntlm_maven_proxy"
         active: true
         protocol: "http"
         username: "jetune"
         password: "mypassword"
         host: "localhost"
         port: 3286
         exclusions: "localhost|127.0.0.1|some.other.host"
      maven_servers:
       - id: "sonatype-nexus"
         username: "admin"
         password: "admin"
       - id: "bitbucket"
         privateKey: "/opt/security/key"
         passphrase: "p@ssw0rd"
      maven_mirrors:
       - id: "mirror-central"
         name: "Central maven repository mirror"
         target: "central"
         url: "https://artifact.lab.kube-cloud.be/repository/maven-central/"
