---
- name: Converge
  hosts: all

  roles:
   - role: jetune.java
     vars:
      from_repo: false
      implementation: OPENJDK
      v_major: 8
      v_minor: 40
      build: 25
      os: linux
      arch: x64
      date: 10_feb_2015
      checksum: md5:4980716637f353cfb27467d57f2faf9b
      alternative_priority: 300
      is_default: true

   - role: ansible-role-maven
     vars:
      maven_v_major: 3
      maven_v_minor: 2.5
      maven_is_default: true
      maven_user: "root"
      maven_group: "root"
      maven_local_repository: "/opt/maven/repository"
      maven_proxies:
       - id: "cntlm_maven_proxy"
         active: true
         protocol: "http"
         username: "jetune"
         password: "mypassword"
         host: "localhost"
         port: 3286
         exclusions: "localhost|127.0.0.1|some.other.host"
      maven_servers:
       - id: "sonatype-nexus"
         username: "admin"
         password: "admin"
       - id: "bitbucket"
         privateKey: "/opt/security/key"
         passphrase: "p@ssw0rd"
      maven_mirrors:
       - id: "mirror-central"
         name: "Central maven repository mirror"
         target: "central"
         url: "https://artifact.lab.kube-cloud.be/repository/maven-central/"
